version: "3.9"

services:
  db:
    image: postgres:14.5
    container_name: "gsk_db"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gsk
      - POSTGRES_USER=gsk
      - POSTGRES_PASSWORD=gskpostgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: gsk_db_admin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: wsi.haidr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /var/lib/pgadmin
  api:
    container_name: "gsk_django"
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./scorekeeper:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
