version: "3.9"

services:
  db:
    image: postgres:14.5
    container_name: "gsk_db"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gsk
      - POSTGRES_USER=gsk
      - POSTGRES_PASSWORD=gskpostgres
  api:
    container_name: "gsk_django"
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
