export const BASE_API_URL = "http://localhost:8000"
export const GAME_ENDPOINT = "/game/"
export const PLAYER_LIST_ENDPOINT = "players"
export const PLAYER_DETAIL_ENDPOINT = "player"
export const PLAYER_RU_ENDPOINT = "player/ru"