# Generated by Django 4.1.3 on 2022-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avatar',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
