# Generated by Django 4.1.2 on 2022-10-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.AlterField(
            model_name='player',
            name='drawn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='lose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='scores_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='win',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
