# Generated by Django 4.1.2 on 2022-10-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_rank_alter_player_drawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'In Play'), ('E', 'Ended')], default='C', max_length=2),
        ),
    ]
