# Generated by Django 4.1.2 on 2022-10-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_match_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('points', models.FloatField()),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='match',
            name='play',
        ),
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='matchrow',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.match'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PlayerMatchResult',
        ),
        migrations.AddField(
            model_name='playermatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.match'),
        ),
        migrations.AddField(
            model_name='playermatch',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
