# Generated by Django 4.1.3 on 2022-11-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_playermatch_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
