# Generated by Django 4.1.2 on 2022-10-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playermatch_remove_match_play_remove_match_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrow',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchrow',
            name='score',
        ),
        migrations.CreateModel(
            name='MatchRowIndividualScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.matchrow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
