# Generated by Django 4.1.2 on 2022-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_matchrow_player_remove_matchrow_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrowindividualscore',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.matchrow'),
        ),
    ]
