# Generated by Django 4.1.2 on 2022-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_matchrowindividualscore_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='drawn',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lose',
        ),
        migrations.AddField(
            model_name='player',
            name='points_average',
            field=models.FloatField(default=0),
        ),
    ]
