# Generated by Django 4.1.2 on 2022-10-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_player_drawn_remove_player_lose_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='user', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'name')},
        ),
        migrations.RemoveField(
            model_name='player',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
